data:
  block_size: 128
  root: "$HOME/projects/vermissa/data/book=sherlock"
  download_url: "https://www.gutenberg.org/cache/epub/3289/pg3289.txt"
model:
  name: "gpt2"
  output_dir: "$HOME/projects/vermissa/models/model=gpt2/book=sherlock"
  pretrained:
    pretrained_model_name_or_path: "gpt2"
  training:
    per_device_train_batch_size: 4
    num_train_epochs: 3
    logging_steps: 500
    save_steps: 1000
    logging_dir: "$HOME/projects/vermissa/logs/model=gpt2/book=sherlock"
    report_to: []
  generate:
    max_new_tokens: 50
    do_sample: True
    top_k: 50
    top_p: 0.95
    temperature: 0.8
    repetition_penalty: 1.2
